# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApeGui < Formula
  desc "AWS Platform Explorer — browse EC2 files and S3 buckets from your browser"
  homepage "https://github.com/Dongckim/A.P.E"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.2/ape-darwin-amd64.tar.gz"
      sha256 "b5ddf75acafdc8450fa4b9b120edbf69ac55d659f6ffde8992430d65cfe8cf2e"

      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.2/ape-darwin-arm64.tar.gz"
      sha256 "be06baf7b0a601d8b4db5c456843018a44649e693bd4c5ca49972a986679aafd"

      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.2/ape-linux-amd64.tar.gz"
      sha256 "f450cb4b409fb2fb76f63b8f17c41f27662022a0a753552b8aa213d9712f2f48"
      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.2/ape-linux-arm64.tar.gz"
      sha256 "af44323ab43b650ae8ac124c832a89570d4d2ad5c691b39347f8f91e31e08a30"
      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  test do
    assert_match "A.P.E", shell_output("#{bin}/ape --version 2>&1", 1)
  end
end
