# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ape < Formula
  desc "AWS Platform Explorer — browse EC2/S3/RDS PostgreSQL from your browser"
  homepage "https://github.com/Dongckim/A.P.E"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.4.0/ape-darwin-amd64.tar.gz"
      sha256 "271fbaa52eb866c9657105723bb529cffd6262995ef4300bd117f93fb065fc46"

      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.4.0/ape-darwin-arm64.tar.gz"
      sha256 "543c9fbd49a4695fb93403d035689b6fc41c7c9a74d742d052008b39d5c4505c"

      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.4.0/ape-linux-amd64.tar.gz"
      sha256 "2d9121aeb8288280ea742c448b37831403776babf84edfc840b9f618c9697a73"
      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.4.0/ape-linux-arm64.tar.gz"
      sha256 "55a4216725d729c101c1ad8c605528fd04115ff73615192a38059e41bbd5954d"
      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  test do
    assert_match "A.P.E", shell_output("#{bin}/ape --version")
  end
end
