# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ape < Formula
  desc "AWS Platform Explorer — browse EC2 files and S3 buckets from your browser"
  homepage "https://github.com/Dongckim/A.P.E"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.1/ape-darwin-amd64.tar.gz"
      sha256 "77956056ecb5c6566321fa119fc07db378cfe1c96f0546ee067e59b7e25bba46"

      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.1/ape-darwin-arm64.tar.gz"
      sha256 "2b18b70189776ca5ecb5abc578dc4f711efb302a63844ebc9b70b1c5e09785bf"

      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.1/ape-linux-amd64.tar.gz"
      sha256 "f69af5b63d1cd543a85facd1e2507def81cf0d9ddfa982f3921f7ee61fd0bdec"
      define_method(:install) do
        bin.install "ape"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dongckim/A.P.E/releases/download/v0.3.1/ape-linux-arm64.tar.gz"
      sha256 "b46ed50da7c4f01b019b69563c9af93f1931776200f692bf8b6372ed4f601f76"
      define_method(:install) do
        bin.install "ape"
      end
    end
  end

  test do
    assert_match "A.P.E", shell_output("#{bin}/ape --version 2>&1", 1)
  end
end
